spring:
  datasource:
    url: jdbc:h2:mem:financial
    username: cvc
    password: cvc
    driverClassName: org.h2.Driver
  h2.console.enable: true
  h2.console.path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: drop-and-create #validate